mysite/blog/urls.py
from django.urls import path
from . import views
from .views import post_list, post_detail, blog_home, add_comment, user_logout, user_login, user_signup

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required


urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post/<int:pk>/', post_detail, name='post_detail'),
    path('home/', blog_home, name='blog_home'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>/edit/', login_required(views.post_edit), name='post_edit'),
    path('add_comment/<int:post_pk>/', views.add_comment, name='add_comment'),
    path('signup/', views.user_signup, name='signup'),
    path('login/', views.user_login, name='user_login'),
    path('logout/', user_logout, name='user_logout'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

mysite/blog/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.contrib.auth.models import AbstractUser,  BaseUserManager
from django.contrib.auth.backends import BaseBackend

class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now, editable=False)
    published_date = models.DateTimeField(blank=True, null=True, default=timezone.now)
    edited_date = models.DateTimeField(null=True, blank=True)
    featured_image = models.ImageField(upload_to='featured_images/', blank=True, null=True)


    def publish(self):
        self.published_date = timezone.now()
        self.save()


    def __str__(self):
        return f'{self.title} by {self.author}'


class Comment(models.Model):
    post = models.ForeignKey('Post', on_delete=models.CASCADE, related_name='comments')
    author = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'{self.text} by {self.author}'

mysite/blog/forms.py
from django import forms
from . import views
from .models import Post, Comment
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'text',)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class CustomAuthenticationForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ['username', 'password']

mysite/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .models import Post, Comment
from .forms import PostForm, CommentForm, CustomUserCreationForm, CustomAuthenticationForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
#from django.core.validators import EmailValidator
from django.contrib import messages
from django.core.exceptions import ValidationError
from django.contrib.auth.views import  LoginView
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView


def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    #posts = Post.objects.filter(published_date__lte=timezone.now())

    paginator = Paginator(posts, 10)  # Show 10 posts per page

    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(request, 'blog/post_list.html', {'posts': posts})


def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    comments = post.comments.all()

    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('post_detail', pk=post.pk)
    else:
        comment_form = CommentForm()

    return render(request, 'blog/post_detail.html', {'post': post, 'comments': comments, 'comment_form': comment_form})



def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.edited_date = timezone.now()
            post.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'blog/post_edit.html', {'form': form})



def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    comments = Comment.objects.filter(post=post)

    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = CommentForm()

    return render(request, 'blog/post_detail.html', {'post': post, 'comments': comments, 'form': form})


@login_required
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)

    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)

    return render(request, 'blog/post_edit.html', {'form': form, 'post': post})



def add_comment(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)

    if request.method == "POST":
        if request.user.is_authenticated:  # Check if the user is logged in
            form = CommentForm(request.POST)
            if form.is_valid():
                comment = form.save(commit=False)
                comment.post = post
                comment.author = request.user  # Assign the logged-in user as the author
                comment.save()
                return redirect('post_detail', pk=post.pk)
        else:
            # show a message and a redirect to prompt the user to log in
            messages.info(request, 'Please log in to add a comment.')
            return redirect('user_login')
    else:
        form = CommentForm()

    return render(request, 'blog/add_comment.html', {'form': form, 'post': post})



def blog_home(request):

    return redirect('post_list')


def user_signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, f'Welcome, {user.username}! You have successfully signed up.')
            return redirect('blog_home')
    else:
        form = CustomUserCreationForm()

    return render(request, 'blog/signup.html', {'form': form})


def user_login(request):
    if request.method == 'POST':
        form = CustomAuthenticationForm(request, request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, f'Welcome back, {username}!')
                return redirect('blog_home')
            else:
                messages.error(request, 'Invalid username or password.')
    else:
        form = CustomAuthenticationForm(request)
    return render(request, 'blog/login.html', {'form': form})



def user_logout(request):
    logout(request)
    messages.success(request, 'You have been successfully logged out.')
    return redirect('blog_home')

mysite/blog/templates/blog/add_comment.html
<!-- blog/templates/blog/add_comment.html -->

{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Share Your Insights</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
  <div class="container">
    <div class="row">
      <div class="col-md-8 offset-md-2">
        <h1 class="text-center mt-5">Join the Conversation</h1>
        <p class="lead text-muted">Add your thoughts and engage with community.</p>

        <form method="POST" class="comment-form mt-4">
          {% csrf_token %}

          <div class="form-group">
            <label for="id_text">Comment: </label>
            {{ form.text }}
          </div>
          <input type="hidden" name="post_pk" value="{{ post.pk }}">
          <button type="submit" class="btn btn-success btn-lg">Share Your Insights</button>
        </form>

        <div class="mt-4 text-center">
          <a href="{% url 'post_detail' post.pk %}" class="btn btn-secondary">Back to Post</a>
        </div>
      </div>
    </div>
  </div>
</body>
</html>

mysite/blog/templates/blog/base.html
{% load static %}

<!DOCTYPE html>

<html

lang="en">

<head>


<meta

charset="UTF-8">


<meta

name="viewport"

content="width=device-width, initial-scale=1.0">


<title>{% block title %}My Blog{% endblock %}</title>


<link

rel="stylesheet"

href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">


<link

rel="stylesheet"

href="{% static 'blog/styles.css' %}">
</head>
<body>
  <header>
      <div class="container">
          <a href="{% url 'post_new' %}" class="top-menu">
             {% include './icons/file-earmark-plus.svg' %}
         </a>

      </div>
  </header>
  <main>
    <div class="container">
      {% block content %}{% endblock %}
    </div>
  </main>
  <footer>
    </footer>
</body>
</html>

mysite/blog/templates/blog/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Welcome Back!</title>
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body class="login-page">
  <div class="container">
    <div class="row justify-content-center align-items-center" style="height: 100vh;">
      <div class="col-md-6">
        <h1 class="text-center mb-4">Welcome Back!</h1>
        <form method="POST" class="login-form">
          {% csrf_token %}
          {% if messages %}
            <ul class="messages">
              {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
              {% endfor %}
            </ul>
          {% endif %}
          <div class="form-group">
            <label for="{{ form.username.id_for_label }}">Username</label>
            {{ form.username }}
          </div>
          <div class="form-group">
            <label for="{{ form.password.id_for_label }}">Password</label>
            {{ form.password }}
          </div>
          <button type="submit" class="btn btn-primary btn-block">Log In</button>
        </form>
        <p class="text-center mt-3">Don't have an account? <a href="{% url 'signup' %}">Sign Up</a></p>
      </div>
    </div>
  </div>
</body>
</html>

mysite/blog/templates/blog/post_detail.html
<!-- blog/templates/blog/post_detail.html -->


{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{{ post.title }}</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'css/blog.css' %}">
</head>
<body>
  <div class="container">
    <div class="row">
      <div class="col-md-8 offset-md-2">
        <div class="post-detail">
          <h1 class="post-title">{{ post.title }}</h1>
          <div class="post-meta">
            <!-- Use the edited_date if available, otherwise use published_date -->
            <p class="date">Edited on
              {% if post.edited_date %}
                {{ post.edited_date|date:"F j, Y" }}
              {% else %}
                {{ post.published_date|date:"F j, Y" }}
              {% endif %}
              by {{ post.author }}
            </p>
            {% if post.featured_image %}
              <img src="{{ post.featured_image.url }}" class="post-img img-fluid mb-3">
            {% endif %}
            {% if request.user == post.author %}
              <a class="btn btn-primary mt-2" href="{% url 'post_edit' post.pk %}">Edit Post</a>
            {% endif %}
          </div>
          <div class="post-content">
            {{ post.text|linebreaks }}
          </div>
        </div>

        <section class="comments" id="comments-section">
          <h2 class="comments-title text-center mb-4">Join the Conversation</h2>
          <div class="comment-list">
            {% for comment in comments %}
              <div class="comment">
                <div class="comment-header">
                  <div class="comment-author">
                    <img src="{% if comment.author.profile_image %}{{ comment.author.profile_image.url }}{% else %}{% static 'blog/images/default-avatar.png' %}{% endif %}" class="comment-avatar rounded-circle mr-2">
                    <span class="comment-author-name font-weight-bold">{{ comment.author }}</span>
                    <span class="comment-date text-muted">shared on {{ comment.created_date|date:"F j, Y" }}</span>
                  </div>
                </div>
                <div class="comment-body">
                  <p class="comment-content">{{ comment.text|linebreaksbr }}</p>
                </div>
              </div>
            {% endfor %}
            <!-- Display success messages -->
            {% if messages %}
              <div class="alert alert-success mt-2">
                {% for message in messages %}
                  {{ message }}
            {% endfor %}
             </div>
            {% endif %}
          </div>
          <a href="{% url 'add_comment' post.pk %}" class="btn btn-primary btn-lg">Share Your Thoughts</a>
          <a href="{% url 'blog_home' %}" class="btn btn-secondary">Back to Blog</a>
          </div>
        </section>
      </div>
    </div>
  </div>
  <script src="{% static 'blog/blog.js' %}"></script>
</body>
</html>

mysite/blog/templates/blog/post_edit.html
<!-- blog/templates/blog/post_edit.html -->

{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% if post.id %}Edit Post{% else %}New Post{% endif %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'blog/styles.css' %}">
</head>

<body>
    <div class="container">
        <h1 class="mt-5">{% if post.id %}Edit Post{% else %}New Post{% endif %}</h1>

        {% if user.is_authenticated and post.author == user %}
        <form method="POST" class="post-form mt-3">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Save</button>
        </form>
        {% else %}
        <p>You don't have permission to visit this page.</p>
        {% endif %}
    </div>
</body>

</html>

mysite/blog/templates/blog/post_list.html
<!-- blog/templates/blog/post_list.html -->


{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Spark Collective</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'css/blog.css' %}">
</head>
<body>
  <div class="container">
    <header class="blog-header py-3">
      <h1 class="blog-title">The Spark Collective</h1>
      <p class="lead blog-description">A blog that contains unfiltered thoughts, untamed ideas, and unapologetic creativity. From Spark to Flame: Collective Journeys of Creation.</p>
    </header>

    <!-- Display login/logout buttons -->
    <div class="text-end mb-3">
      {% if user.is_authenticated %}
        <a href="{% url 'user_logout' %}" class="btn btn-outline-danger">Logout</a>
      {% else %}
        <a href="{% url 'user_login' %}" class="btn btn-outline-primary">Login</a>
      {% endif %}
    </div>


    <div class="row">
      {% for post in posts %}
        <div class="col-md-6">
          <div class="card mb-4">
            {% if post.featured_image and post.featured_image.url %}
              <img src="{{ post.featured_image.url }}" class="card-img-top" alt="{{ post.title }}">
            {% endif %}
            <div class="card-body">
              <h2 class="card-title">{{ post.title }}</h2>
              <p class="card-text">{{ post.excerpt|truncatewords:50 }}</p>
              <a href="{% url 'post_detail' pk=post.pk %}" class="btn btn-primary">Read More</a>
            </div>
            <div class="card-footer">
              <p class="card-text font-italic" style="font-family: 'Playfair Display', serif;">
                Written by {{ post.author }} on {{ post.published_date|date:"F j, Y" }}
              </p>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>

    <div class="pagination">
      {% if is_paginated %}
        {% if page_obj.has_previous %}
          <a class="btn btn-outline-primary" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}
        {% for num in page_obj.paginator.page_range %}
          {% if page_obj.number == num %}
            <span class="btn btn-primary">{{ num }}</span>
          {% else %}
            <a class="btn btn-outline-primary" href="?page={{ num }}">{{ num }}</a>
          {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
          <a class="btn btn-outline-primary" href="?page={{ page_obj.next_page_number }}">Next</a>
        {% endif %}
      {% endif %}
    </div>
  </div>
</body>
</html>

mysite/blog/templates/blog/signup.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Join the Community!</title>
  <link rel="stylesheet" href="{% static 'css/signup.css' %}">
</head>
<body class="signup-page">
  <div class="container">
    <div class="row justify-content-center align-items-center" style="height: 100vh;">
      <div class="col-md-6">
        <h1 class="text-center mb-4">Create Your Account</h1>
        <form method="POST" enctype="multipart/form-data" class="signup-form">
          {% csrf_token %}

          <!-- Display non-field errors -->
          {% if form.non_field_errors %}
            <div class="alert alert-danger">
              <ul>
                {% for error in form.non_field_errors %}
                  <li>{{ error }}</li>
                {% endfor %}
              </ul>
            </div>
          {% endif %}

          <!-- Display form fields -->
          <div class="form-group">
            <label for="{{ form.email.id_for_label }}">Email</label>
            {{ form.email }}
          </div>
          <div class="form-group">
            <label for="{{ form.username.id_for_label }}">Username:</label>
            {{ form.username }}
          </div>
          <div class="form-group">
            <label for="{{ form.password1.id_for_label }}">Password</label>
            {{ form.password1 }}
          </div>
          <div class="form-group">
            <label for="{{ form.password2.id_for_label }}">Confirm Password</label>
            {{ form.password2 }}
          </div>
        <!--
          <div class="form-group">
            <label for="{{ form.profile_picture.id_for_label }}">Profile Picture</label>
            {{ form.profile_picture }}
          </div>
        -->

          <button type="submit" class="btn btn-success btn-block">Sign Up</button>
        </form>
        <p class="text-center mt-3">Already have an account? <a href="{% url 'user_login' %}">Log In</a></p>
      </div>
    </div>
  </div>
</body>
</html>